//
//  ReasonsData.swift
//  Sydney's App
//
//  Created by Micah Wilson on 10/31/15.
//  Copyright © 2015 Micah Wilson. All rights reserved.
//

import UIKit

class ReasonsData {
    static var titles:[String] = ["Your Laugh","Your Smile","Your Spirit","Your Touch","Your Hair","Your Attitude","Your Sense of Humor", "Your Testimony", "Your Love", "You Try", "You're Smart", "You Flirt", "You're Talented", "You're Humble", "You're Loving", "You're Fun", "You care", "Your Family", "The Way you Look at Me", "You're Responsible", "You're Beautiful", "You Make Me Happy"]
    static var images:[UIImage] = [
        UIImage(named: "CMP_7986")!,
        UIImage(named: "IMG_1998")!,
        UIImage(named: "IMG_0688")!,
        UIImage(named: "CMP_8460")!,
        UIImage(named: "CMP_8851")!,
        UIImage(named: "IMG_1383")!,
        UIImage(named: "IMG_1695")!,
        UIImage(named: "IMG_1743")!,
        UIImage(named: "IMG_1446")!,
        UIImage(named: "IMG_1416")!,
        UIImage(named: "IMG_Smart")!,
        UIImage(named: "IMG_Flirt")!,
        UIImage(named: "IMG_Drawing")!,
        UIImage(named: "IMG_Car")!,
        UIImage(named: "IMG_2444")!,
        UIImage(named: "IMG_1703")!,
        UIImage(named: "IMG_2580")!,
        UIImage(named: "IMG_Family")!,
        UIImage(named: "IMG_2679")!,
        UIImage(named: "IMG_1191")!,
        UIImage(named: "CMP_6412")!,
        UIImage(named: "IMG_2467")!]
    static var stories:[String] = [
        "The 1st reason why I love you is because of your laugh. Ever since the first day that I met you I’ve loved the way you laugh, I love the way at me and how I can always say something stupid and even though it’s stupid you’ll laugh. You think that I’m funny which makes me the happiest person. Remember when we talked about loving each other by sending your computer with a youtube video into your room and you would send it back to me with another video, all through Jacob because I wouldn’t break the honor code? I can still hear your laugh through the hallway coming from your room when I’d send a video in. Remember when we used to flirt all the time and joke about getting married. Even before we were dating you were always one of those girls that would laugh at every joke I made when a lot of girls would get scared by something like that. You took it for what it was and just laughed. I love you Sydney because you laugh and I hope I can fill your next year with laughter!",
        "The 2nd reason why I love you is because of your smile. Sydney you have the most incredible smile, and that’s not even mentioning the fact that you always have one! I’m so grateful that you are always smiling and keep me happy all of the time! You can easily tell from any picture that you are a happy girl, I think people can tell you’re happy about this marriage because of how big your smile is in all of our pictures. It looks perfect because you have perfectly white teeth. Sydney you just have the cutest smile and I can’t believe that I get to wake up next to your smiling face everything single morning! How did I get so lucky? I hope you keep smiling until the day you die. Scratch that you can just die with a smile, except that might be a little creepy but YOLO. I’m glad for you’re smile because it makes it really easy for me to tell when something is wrong so I can fix it. Sydney I love your Smile.",
        "The 3rd reason why I love you is because of your spirit. Don’t get this mixed up with your testimony because although I love that very much your spirit is something different. I think that our spirits just match and that’s why I love it. I know I told you I didn’t believe in the idea of a soulmate, but if there were any two soulmates out there then it would be you and me. By your spirit I mean the way you carry yourself, the way you think, and the way you act. I’m grateful for you because I always know you’ll be driven to do the right thing! Remember that time when we decided we were going to do service together so you signed up for Y-Serve? I remember it and although you only went once and I never even went I still remember it and how excited you were to go. It’s those types of decisions that make up the reasons that I love you. I’ll be forever grateful for your spirit. I hope that you’ll always be able to be open with me about how you feel and what you think, I know if we are we’ll be okay. I love you Sydney and especially your spirit.",
        "The 4th reason why I love you is because of your touch. Sydney our lips can touch and our cheeks can brush. Remember that time when I kissed you on the cheek in the hot tub or when I brushed my cheek across yours in Cafe Rio because I wanted to feel your scruff. I love when you touch me when it’s a kiss on the cheek or just when you grab my hand when we are walking to school. You make me feel good inside and I always feel so comfortable when you are in my arms. There is no one I’d rather walk across campus and hold hands with then you. I know I told you I don’t like kissing in public but you can kiss me anytime! I love touching you because It just feels right, I feel good when we are together and just safe. I feel like nobody can harm us as long as we are side by side and hope that you feel the same. I am just so excited to be able to go to sleep together and be able to feel your touch all night every night. Sydney I love the way you touch me.",
        "The 5th reason why I love you is because of your hair. Sydney there is nothing more that I love than long hair and I’m glad you feel the same, I’d still love you if you cut your hair short though. I love when your hair was brown and then I fell in love with your hair when it became blonde. I could sit and play with your hair all day, remember how it costs like 130 dollars to do your hair? Well it’s with it because your hair is incredible! That’s why I don’t like it in a bun or pulled back because your hair looks incredible and it deserves to be flaunted. I know you think I have great hair but when It is compared to yours mine might as well be a buzz cut or a mullet. My favorite thing to do with your hair is to take a little bit of it and see how many times I can wrap it around your ear. :) I don’t know why I love that so much but I like doing it. Anyway Syd whether your hair was blonde, brown, or red, I would be in love with it. Anyway I love your hair, especially because it goes perfect with your smile and laugh.",
        "The 6th reason why I love you is because of your attitude. Sydney I’ve never seen anyone with as positive of an attitude as you have, you are so full of service and I completely feel like you would do anything for me. It’s hard for me to find a time you aren’t happy (not counting the time your were on those birth control pills). What I love about your attitude most is that every time I have a negative attitude you have a positive one, and the few times your might not have the best attitude I usually have a good attitude so I think they go together perfect! I love how your attitude goes along perfectly with the situation we are in. The time I remember is when we are in St. George over valentines day and you decide you want to rap some crazy song and I remember smiling and laughing and thinking it was the greatest thing in the world. It’s times like that I can see you have a great attitude and you truly are where you are. I’m grateful for you always giving me a good attitude by you having a great one. I love your attitude Sydney.",
        "The 7th reason why I love you is because of your sense of humor. Haha I think you are the funniest girl, you always know how to make me laugh. Not only are you funny but you are cute when you do it. The funniest thing I think you have ever done is you rejected me when I tried to kiss you after you had already told Ali that you wanted to marry me! Only someone with a sense of humor like you would have the audacity to do that! ;) Ha I’m really grateful that your sense of humor can keep up with mine, not too many peoples can. I’m excited to marry you because you can always make me laugh and it’s not even always in things you say, half of the times it’s in what you do. I know that our marriage will be filled with inside jokes and plenty of room to laugh together. I know you will always keep me laughing, some of the times at you but most of the time with you! I read once that a sense of humor can be a bad thing. But I think that yours is perfect! Sydney I love your sense of humor!",
        "The 8th reason why I love you is because of your testimony. Remember the time when I was leaving your apartment because it was 12:00 and you walked me out to my car but instead of saying goodbye you just got in my car so we drove to the temple and sat out in front of the temple talking until 4 in the morning It was this time that I fell in love with your testimony and I knew that I wanted to marry you. I know you don’t know everything about the gospel but you know enough and you let it drive you and influence your decisions. It seems like all of the parts of my testimony that are weak are where yours are the strongest and where yours are the weakest mine are the strongest and I’m so very grateful for the love of the Savior and our Heavenly Father that you have! It really is inspiring to watch that part of you. I know with you I’ll continue to grow into a better person and grow in making better decisions. I’m grateful your willing to serve God in whatever aspect he asks you to serve. I love you testimony Sydney.",
        "The 9th reason why I love you is because of your love. The most incredible thing about love is you can feel it from others. Sydney I can feel your love, it’s so strong. I know you love me and I can see it in every single way it can possibly be expressed. I’ve never met anyone with such a great capacity to love someone! It just amazes me how you are able to show it in so many ways and I hope I can get better at showing my love back. Remember when we took a picture with that pillow that says ‘Love you more” at Kasandra’s wedding reception and it got like a ton of likes on Facebook and everybody thought that we were engaged. Well the words on that pillow are true. I don’t know who loves each other more out of the two of us, but I know I love you more than anything or anyone on this entire planet and I know that you feel the same and I’m so grateful for that. I hope we can continue to show our love in such a positive and fulfilling way for the rest of our lives. Sydney I’m in love with your love!",
        "The 10th reason why I love you is because you try. Remember that time we went up to Hannah’s cabin and we spent the weekend fulfilling dares, riding the razor, and fishing. This picture is a perfect example of how you try. Sydney you are always willing to do something new and you have a good attitude. Most girls would be disgusted to hold a fish or afraid of going out of their comfort zone but you are willing to jump off big cliff and surf at flowrider. I love that even though you might never understand how to program you will at least listen to me trying to explain things. You try in school, you sit in the front row and talk to the teacher after class and email the TA’s. Not many people do that and your grades show because of your effort. You try to make everyone happy and try to do what’s best for them. I’m grateful you try in our relationship and that you will be willing to try my crazy things with me! (Skinny dipping in the ocean) I know that no matter how scared you are of something you will at least try and I love you for that.",
        "The 11th reason why I love you is because you're smart. I did some research and I don’t know if you know this but the average GPA at BYU for graduates graduating with a bachelors degree is 3.3. I know you have a lot higher than that! You were able to get into the nursing program even though this is probably one of the most competitive semesters to be trying to get into the nursing program. I love how smart you are, I’m glad you can have an intelligent conversation with me. You are doing so good in your classes even though this has been the craziest semester of both yours and my life. Not only are you smart but you love to learn. You get excited about chemistry, and you love learning. Because of that I know that you’ll never stop. Now I’ll be able to spend the rest of my life learning things from you. I hope we’ll be able to continue learning together for the rest of our lives and then take that with us into the eternities and spend eternity learning and growing. I love how smart you are Sydney.",
        "The 12th reason why I love you is because you flirt. Remember how we would flirt with each other even when we were dating other people? Haha that’s when you know! I love how much fun it was to joke and flirt the entire time we’ve been in a relationship. I’ll always remember how we had a 9 month long engagement because you asked me to marry you on our trip over valentines day. Or that time you thought you wouldn’t get married until you were 29 and I told you we didn’t have to wait that long if you didn’t want to. I’m glad you made the right decision on that one. I love how you tell me I’m cute and when you tell me the things that you love about me. I’m excited to flirt with you for years to come and especially when we are old together. Just imagine old Syd and old Micah flirting with each other all day, I can’t wait for it. Most girls know how to flirt but not as many girls know how to be flirted with, but I know if I flirt with you that you are gonna send it right back at me. I love how flirty you are.",
        "The 13th reason why I love you is because you're talented. I’ll never forget the first time that you showed me your art from your AP art class and some of the other classes you’ve been in. It’s all so incredible! I know this picture isn’t an actually drawing of you and I but it was my last attempt to get you to draw a picture of us together. You’re are a wonderful artist but you’re talented in so many ways! You seriously have the voice of a Goddess, I don’t know what a Goddess sounds like but I imagine they sound like you. You won the state championship in soccer like every year, and pretty amazing that you are talented enough to be on a team that is that good. You’re a talented cook and you always make the best meals for me. I know you’re scared to play tennis with me but you’ll do great, you’re great at everything that you do. I hope we can find some hobbies that we can both become good at together and then do those things for the rest of our lives, I’m so excited to figure out what they’ll be. Sydney I love you talent.",
        "The 14th reason why I love you is because you're humble. One of the single things I love you for most is that you are never willing to argue. That shows how humble you are, you don’t always have to be right and I hope you’ll be able to teach me that principle and make it stick with me at one point. They say that opposites attract and I think that’s true in most cases because when it comes to humility you are a lot further along the path than I am. I’ve seen you become a better person because of you’re humility. You are always willing to change something to make things better even if you aren’t the one that is wrong, I’ve seen that with you in school, with your family, and with me. Humility is one of the most important thing that Christ taught when he was one the earth and I think it’s one of the first attributes we have to master before we can master the other ones, It’s really important and I’m grateful for how much humility you have and you’re desire to become more and more humble. I love you’re humility Sydney.",
        "The 15th reason why I love you is because you're loving. You are so full of love for others. You’re incredibly patient to be able to put up with me and my friends but it doesn’t stop there because you are even loving towards Whiskers and Lenny. Even when Lenny is being a bad boy you are always so loving towards him. You love my friends and really everyone around you. I know you’ll just be the most perfect mother because you know how to love. You are so loving to those around you. It’s amazes me every time we are on campus or somewhere and you see somebody from high school or someone that you know but haven’t seen in a while and the first words out of your mouth are always “look how cute you are” or “you’re so cute”. It’s that kind of love for other that will make you the most perfect nurse, perfect mother, and perfect husband. I know that no matter who we live next to or what decisions that our kids make you will just show them love and love is what will hold our family together. I love how loving you are.",
        "The 16th reason why I love you is because you're fun. Remember how you always want to brush our teeth together, brushing your teeth isn’t fun but you make it fun. You’re probably able to make my Calculus class fun! It doesn’t really matter what we are doing, we could be cliff jumping or just watching a movie and I always have fun with you. See the thing is I find fun in skipping class but you find fun in the class and that is what I love about you! You don’t have to be doing anything particularly fun to have fun. Life is fun for you Sydney and if it’s not then you make it fun. I hope that together we will be able to make every aspect of our live fun together. Remember when we would be together at midnight and you would always want to go get kiddy cones from McDonalds together. I’d much rather just have a big ice cream cone but the kiddy cones are fun and that’s why we do it. I love having fun with you and I’m glad you know how to create that fun when I don’t. Sydney I love how much fun you are.",
        "The 17th reason why I love you is because you care. One of the best memories I have with you is when we went to California together to hang out at the beach and to go to disneyland and just have fun. One of the things I remember and loved is when we would go visit the members I served with or when we went to the fireside with all of the missionaries and you actually cared. You cared about the people and you cared about the missionaries that I wanted to see and you cared about me. I’m so in love with how much you care about me and how much you show me you care. You are willing to wake me up every morning  and I know if I ever got sick you would be right there to make me soup or to get me whatever I needed. Hopefully that will never happen but If it did I know that you would take good care of me. You don’t only care about me but you care about all of the things that I care about as well and I like that. I’m glad you feel like things are important if I feel that way about them. I love how much you care.",
        "The 18th reason why I love you is because of your family. I know it might now always seem like it but I love you family. It just takes me a little while to warm up to people but don’t worry I’ll get there for sure. I love that they raised you the way that they did or else I might not have ever fallen in love with you. I love doing things with your family and I like how close you all are together. Even though I have the family group messages on do not disturb I enjoy reading the messages that they all send to each and how everyone always has something to say about everything. I’m really excited to go to Lake Powell with all of them and make more memories and get to know them all a lot better. Even though I haven’t even met Sterling and Sarah I’m sure that I will love them just as much as I love all of your other siblings. I’m grateful for all of them, I love Crew and I’m sure I’ll love Will and Claire just as much. I look forward to spending a lifetime with them and that you’ll be by my side to do so. I love you family Sydney.",
        "The 19th reason why I love you is because of the way you look at me. I love how when we are watching a move that you don’t really care about you always just look up at me and stare at me. It’s kind of weird but I like it anyway. I love how when you look at me you always smile and I love how when you walk out of Humanities class and see me there waiting for you your face always lights up and you get happy. It’s those looks that you give me that make me fall deeper and deeper in love with you each day. One time you told me that you look at me and only see my potential and that’s what I need. I’m grateful you look at me in such an inspiring way and I hope you will always be able to look at me and see a better version of me than I really am. I hope that you can look at me and see the Atonement working in my life, and ultimately I hope you can look at me and see the Saviors light; I hope we can get to that point. I can truly feel you love when you look at me like you do. I just love the way you look at me.",
        "The 20th reason why I love you is because you're responsible. Haha I hope you laughed when you saw this picture but only a truly responsible person would get sorted into Gryffindor, that is more proof than anything I could say that you are responsible and loyal and all those other good attributes. You always are accountable to yourself and you always get your homework done on time. One thing that I think is great is that you actually study for tests and you study hard and long. I’ve never really been like that but it takes a lot of dedication and it shows how responsible you are. I hope that you’ll do crazy stuff with me throughout our lives but I also hope that while we are doing that you make sure that we don’t go to jail ;) This also falls under the category of being clean, you always fold your laundry, make sure the dishes are done, and make sure that dinner is cooked. Hopefully one day I’ll be able to be as responsible as you are, well maybe. Anyway I think you are great and I love that you’re responsible.",
        "The 21st reason why I love you is because you're beautiful. Sydney I can’t help but to think you are the most beautiful girl in the world, everything about you is absolutely beautiful. I remember the first time I really thought you were beautiful was when we went to watch the Lazarus Effect together. Afterwards we just walked around the parking lot and talked for a while and you told me you wanted to be a nurse, then later we talked about how neither of us would get married or even liked anyone and how we thought everyone at BYU was stupid and didn’t really know what love was. That night I realized how beautiful you were. Beauty is a very different thing from being cute or looking pretty. I definitely thought you were those things from the beginning but to find someone beautiful means so much more than those things. Sure you are beautiful in appearance but you are more than that! Sydney you are a beautiful person! I’m glad I get to spend the rest of forever with you because you are so beautiful.",
        "The 22nd reason why I love you is because you make me happy. I’ve never been so happy in my entire life. I knew from the first time that we kissed that you could make me happy for the rest of my life. I get sad every time I have to leave your house at night. Just being with you makes me happy, we could be sitting at the table doing homework or we could be cooking dinner together or just snuggling on the couch or on the bed and it makes me so happy. I hope I can make you equally as happy as you make me. One of the happiest moments of my life is when I got down on my knee and asked you to marry me and you said yes. I think the happiest I’ll probably ever be is when we go to the Salt Lake Temple together and kneel across the altar and are sealed for all time and eternity, I can’t imagine any other way to spend my life. I’m so happy I get to spend every day and every night with you by my side because I know that every day and every night I will be happy. I wish you knew how happy you make me! I love you Sydney Horne."]
}
